<#
.SYNOPSIS
    Cross-compile Rust spice-backend for Android and deploy to jniLibs.
.DESCRIPTION
    Builds libspice_backend.so for all Android ABIs and places them
    into composeApp/src/androidMain/jniLibs/<abi>/.
.NOTES
    Prerequisites (run once):
      rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
#>

$ErrorActionPreference = "Stop"

# ═══════════════════════════════════════════════════════════════════
# Stage 1: Locate Android NDK
# ═══════════════════════════════════════════════════════════════════

Write-Host "`n>>> Stage 1: Locating Android NDK..." -ForegroundColor Cyan

$ndkSearchPaths = @(
    "$env:LOCALAPPDATA\Android\Sdk\ndk",
    "$env:ANDROID_NDK_HOME"
)

$ndkRoot = $null
foreach ($base in $ndkSearchPaths) {
    if ($base -and (Test-Path $base)) {
        $latest = Get-ChildItem $base -Directory -ErrorAction SilentlyContinue `
            | Where-Object { $_.Name -match '^\d+\.\d+' } `
            | Sort-Object { [version]$_.Name } -Descending `
            | Select-Object -First 1
        if ($latest) {
            $ndkRoot = $latest.FullName
            break
        }
    }
}

if (-not $ndkRoot) {
    Write-Host ">>> ERROR: NDK not found." -ForegroundColor Red
    Write-Host "    Install via Android Studio → SDK Manager → SDK Tools → NDK" -ForegroundColor Red
    exit 1
}

$ndkVersion = Split-Path $ndkRoot -Leaf
$toolchainBin = Join-Path $ndkRoot "toolchains\llvm\prebuilt\windows-x86_64\bin"

if (-not (Test-Path $toolchainBin)) {
    Write-Host ">>> ERROR: NDK toolchain not found at:" -ForegroundColor Red
    Write-Host "    $toolchainBin" -ForegroundColor Red
    exit 1
}

Write-Host "    NDK $ndkVersion" -ForegroundColor Green
Write-Host "    Toolchain: $toolchainBin" -ForegroundColor Green

# ═══════════════════════════════════════════════════════════════════
# Stage 2: Setup cargo config for cross-compilation
# ═══════════════════════════════════════════════════════════════════

Write-Host "`n>>> Stage 2: Setting up cargo config..." -ForegroundColor Cyan

$minSdk = 31
$configDir  = ".cargo"
$configFile = Join-Path $configDir "config.toml"

$targets = @(
    @{ target = "aarch64-linux-android";   clang = "aarch64-linux-android"         },
    @{ target = "armv7-linux-androideabi"; clang = "armv7a-linux-androideabi"      },
    @{ target = "x86_64-linux-android";    clang = "x86_64-linux-android"          },
    @{ target = "i686-linux-android";      clang = "i686-linux-android"            }
)

$configContent = "# Auto-generated by build_android.ps1`n# NDK: $ndkVersion   minSdk: $minSdk`n`n"

foreach ($t in $targets) {
    $linker = "$toolchainBin\$($t.clang)$($minSdk)-clang.cmd" -replace '\\', '/'
    $configContent += @"

[target.$($t.target)]
linker = "$linker"
rustflags = [
    "-Clink-arg=-Wl,-z,max-page-size=16384",
    "-Clink-arg=-Wl,-z,common-page-size=16384",
    "-Clink-arg=-Wl,-z,relro",
    "-Clink-arg=-Wl,-z,now",
    "-Clink-arg=-Wl,--enable-new-dtags",
    "-Clink-arg=-Wl,-z,separate-loadable-segments",
]
"@
}

# Only rewrite if NDK path changed (avoids dirtying git)
$currentConfig = if (Test-Path $configFile) { Get-Content $configFile -Raw } else { "" }
if ($currentConfig -ne $configContent) {
    New-Item -ItemType Directory -Force -Path $configDir | Out-Null
    Set-Content -Path $configFile -Value $configContent
    Write-Host "    Wrote $configFile" -ForegroundColor DarkGray
} else {
    Write-Host "    $configFile (unchanged)" -ForegroundColor DarkGray
}

# ═══════════════════════════════════════════════════════════════════
# Stage 3: Build Rust library for each Android ABI
# ═══════════════════════════════════════════════════════════════════

Write-Host "`n>>> Stage 3: Building Rust Library..." -ForegroundColor Cyan

$buildMap = @{
    "aarch64-linux-android"   = "arm64-v8a"
    "armv7-linux-androideabi" = "armeabi-v7a"
    "x86_64-linux-android"    = "x86_64"
    "i686-linux-android"      = "x86"
}

foreach ($target in $buildMap.Keys) {
    Write-Host "    Building $target ..." -ForegroundColor Yellow
    cargo build --release --target $target
    if ($LASTEXITCODE -ne 0) {
        Write-Host "    >>> ERROR: Build failed for $target" -ForegroundColor Red
        exit $LASTEXITCODE
    }
    Write-Host "    $target OK" -ForegroundColor Green
}

# ═══════════════════════════════════════════════════════════════════
# Stage 4: Copy .so files to jniLibs
# ═══════════════════════════════════════════════════════════════════

Write-Host "`n>>> Stage 4: Copying Shared Libraries to jniLibs..." -ForegroundColor Cyan

$scriptDir    = Split-Path -Parent $MyInvocation.MyCommand.Path
$jniLibsBase  = Join-Path $scriptDir "..\composeApp\src\androidMain\jniLibs"

foreach ($pair in $buildMap.GetEnumerator()) {
    $target = $pair.Key
    $abi    = $pair.Value

    $src  = Join-Path $scriptDir "target\$target\release\libspice_backend.so"
    $dest = Join-Path $jniLibsBase $abi

    if (-not (Test-Path $src)) {
        Write-Host "    SKIP: $src not found" -ForegroundColor DarkYellow
        continue
    }

    New-Item -ItemType Directory -Force -Path $dest | Out-Null
    Copy-Item -Path $src -Destination "$dest\libspice_backend.so" -Force

    $size = [math]::Round((Get-Item $src).Length / 1KB, 1)
    Write-Host "    libspice_backend.so → $abi\  ($size KB)" -ForegroundColor Green
}

# ═══════════════════════════════════════════════════════════════════
# Done
# ═══════════════════════════════════════════════════════════════════

Write-Host "`n>>> Done: All targets built and deployed successfully." -ForegroundColor Green
Write-Host ""
